// Generated by PyHDL Transpiler
// Source: C:\Users\tkyke\OneDrive\Desktop\pyhdl\test_code\01_basic_ports.phd

module BasicPorts (
    input logic clk,
    input logic rst,
    input logic enable,
    input logic [7:0] data_in_8,
    input logic [15:0] data_in_16,
    input logic [31:0] data_in_32,
    output logic [7:0] data_out_8,
    output logic [15:0] data_out_16,
    output logic status
);
    always_comb begin
        data_out_8 = data_in_8;
        data_out_16 = data_in_16;
        status = enable;
    end
endmodule

module WidthCalculation (
    input logic [7:0] a,
    input logic [7:0] b,
    output logic [8:0] sum_out,
    output logic [3:0] low_half
);
    always_comb begin
        sum_out = (a + b);
        low_half = a[3:0];
    end
endmodule