// Generated by PyHDL Transpiler
// Source: C:\Users\tkyke\OneDrive\Desktop\pyhdl\test_code\02_operators.phd

module ArithmeticOps (
    input logic [7:0] a,
    input logic [7:0] b,
    output logic [8:0] sum_out,
    output logic [8:0] diff_out,
    output logic [15:0] prod_out,
    output logic [7:0] div_out,
    output logic [7:0] mod_out
);
    always_comb begin
        sum_out = (a + b);
        diff_out = (a - b);
        prod_out = (a * b);
        div_out = (a / b);
        mod_out = (a % b);
    end
endmodule

module BitwiseOps (
    input logic [7:0] a,
    input logic [7:0] b,
    output logic [7:0] and_out,
    output logic [7:0] or_out,
    output logic [7:0] xor_out,
    output logic [7:0] not_out
);
    always_comb begin
        and_out = (a & b);
        or_out = (a | b);
        xor_out = (a ^ b);
        not_out = (~a);
    end
endmodule

module ShiftOps (
    input logic [7:0] data,
    input logic [2:0] shift_amt,
    output logic [7:0] lshift_out,
    output logic [7:0] rshift_out,
    output logic [7:0] lshift_const,
    output logic [7:0] rshift_const
);
    always_comb begin
        lshift_out = (data << shift_amt);
        rshift_out = (data >> shift_amt);
        lshift_const = (data << 2);
        rshift_const = (data >> 3);
    end
endmodule

module CompareOps (
    input logic [7:0] a,
    input logic [7:0] b,
    output logic eq,
    output logic neq,
    output logic lt,
    output logic gt,
    output logic lte,
    output logic gte
);
    always_comb begin
        eq = (a == b);
        neq = (a != b);
        lt = (a < b);
        gt = (a > b);
        lte = (a <= b);
        gte = (a >= b);
    end
endmodule

module LogicalOps (
    input logic a,
    input logic b,
    input logic c,
    output logic and_result,
    output logic or_result,
    output logic not_result,
    output logic complex_result
);
    always_comb begin
        and_result = (a && b);
        or_result = (a || b);
        not_result = (!a);
        complex_result = ((a && b) || (!c));
    end
endmodule