// Generated by PyHDL Transpiler
// Source: C:\Users\tkyke\OneDrive\Desktop\pyhdl\test_code\03_slice_concat.phd

module BitSlicing (
    input logic [15:0] data_16,
    output logic [7:0] high_byte,
    output logic [7:0] low_byte,
    output logic [3:0] nibble,
    output logic single_bit
);
    always_comb begin
        high_byte = data_16[15:8];
        low_byte = data_16[7:0];
        nibble = data_16[11:8];
        single_bit = data_16[0];
    end
endmodule

module BitConcat (
    input logic [3:0] a,
    input logic [3:0] b,
    input logic [7:0] c,
    input logic sel,
    output logic [7:0] concat_8,
    output logic [15:0] concat_16,
    output logic [9:0] concat_with_const
);
    always_comb begin
        concat_8 = {a, b};
        concat_16 = {a, b, c};
        concat_with_const = {sel, 1'd0, c};
    end
endmodule

module MixedSliceConcat (
    input logic [31:0] data_32,
    output logic [31:0] rearranged,
    output logic [15:0] swapped_16
);
    always_comb begin
        rearranged = {data_32[7:0], data_32[15:8], data_32[23:16], data_32[31:24]};
        swapped_16 = {data_32[7:0], data_32[15:8]};
    end
endmodule