// Generated by PyHDL Transpiler
// Source: C:\Users\tkyke\OneDrive\Desktop\pyhdl\test_code\04_comb_logic.phd

module TernaryExpr (
    input logic sel,
    input logic [7:0] a,
    input logic [7:0] b,
    output logic [7:0] mux_out
);
    always_comb begin
        mux_out = (sel ? a : b);
    end
endmodule

module Mux4to1 (
    input logic [1:0] sel,
    input logic [7:0] in0,
    input logic [7:0] in1,
    input logic [7:0] in2,
    input logic [7:0] in3,
    output logic [7:0] out
);
    always_comb begin
        out = 8'd0;
        if ((sel == 0)) begin
            out = in0;
        end else if ((sel == 1)) begin
            out = in1;
        end else if ((sel == 2)) begin
            out = in2;
        end else begin
            out = in3;
        end
    end
endmodule

module PriorityEncoder (
    input logic [3:0] req,
    output logic [1:0] code,
    output logic valid
);
    always_comb begin
        code = 2'd0;
        valid = 1'd0;
        if (req[3]) begin
            code = 2'd3;
            valid = 1'd1;
        end else if (req[2]) begin
            code = 2'd2;
            valid = 1'd1;
        end else if (req[1]) begin
            code = 2'd1;
            valid = 1'd1;
        end else if (req[0]) begin
            code = 2'd0;
            valid = 1'd1;
        end
    end
endmodule

module Decoder2to4 (
    input logic [1:0] sel,
    input logic enable,
    output logic [3:0] out
);
    always_comb begin
        out = 4'd0;
        if (enable) begin
            if ((sel == 0)) begin
                out = 4'd1;
            end else if ((sel == 1)) begin
                out = 4'd2;
            end else if ((sel == 2)) begin
                out = 4'd4;
            end else begin
                out = 4'd8;
            end
        end
    end
endmodule