// Generated by PyHDL Transpiler
// Source: C:\Users\tkyke\OneDrive\Desktop\pyhdl\test_code\05_seq_logic.phd

module SimpleRegister (
    input logic clk,
    input logic [7:0] d,
    output logic [7:0] q
);
    always_ff @(posedge clk) begin
        q <= d;
    end
endmodule

module SyncResetCounter (
    input logic clk,
    input logic rst,
    input logic enable,
    output logic [7:0] count
);
    always_ff @(posedge clk) begin
        if (rst) begin
            count <= 8'd0;
        end else if (enable) begin
            count <= (count + 1);
        end
    end
endmodule

module AsyncResetCounter (
    input logic clk,
    input logic rst,
    input logic enable,
    output logic [7:0] count
);
    always_ff @(posedge clk or posedge rst) begin
        if (rst) begin
            count <= 8'd0;
        end else if (enable) begin
            count <= (count + 1);
        end
    end
endmodule

module AsyncResetNCounter (
    input logic clk,
    input logic rst_n,
    input logic enable,
    output logic [7:0] count
);
    always_ff @(posedge clk or negedge rst_n) begin
        if ((!rst_n)) begin
            count <= 8'd0;
        end else if (enable) begin
            count <= (count + 1);
        end
    end
endmodule

module ShiftRegister (
    input logic clk,
    input logic rst_n,
    input logic serial_in,
    output logic [7:0] parallel_out
);
    always_ff @(posedge clk or negedge rst_n) begin
        if ((!rst_n)) begin
            parallel_out <= 8'd0;
        end else begin
            parallel_out <= {parallel_out[6:0], serial_in};
        end
    end
endmodule