// Generated by PyHDL Transpiler
// Source: C:\Users\tkyke\OneDrive\Desktop\pyhdl\test_code\07_memory.phd

module SinglePortRAM (
    input logic clk,
    input logic we,
    input logic [3:0] addr,
    input logic [7:0] din,
    output logic [7:0] dout
);
    logic [7:0] mem [0:15];
    always_comb begin
        dout = mem[addr];
    end
    always_ff @(posedge clk) begin
        if (we) begin
            mem[addr] <= din;
        end
    end
endmodule

module DualPortRAM (
    input logic clk,
    input logic we_a,
    input logic [3:0] addr_a,
    input logic [7:0] din_a,
    output logic [7:0] dout_a,
    input logic [3:0] addr_b,
    output logic [7:0] dout_b
);
    logic [7:0] mem [0:15];
    always_comb begin
        dout_a = mem[addr_a];
        dout_b = mem[addr_b];
    end
    always_ff @(posedge clk) begin
        if (we_a) begin
            mem[addr_a] <= din_a;
        end
    end
endmodule

module RegisterFile (
    input logic clk,
    input logic rst_n,
    input logic we,
    input logic [2:0] waddr,
    input logic [31:0] wdata,
    input logic [2:0] raddr1,
    output logic [31:0] rdata1,
    input logic [2:0] raddr2,
    output logic [31:0] rdata2
);
    logic [31:0] regs [0:7];
    always_comb begin
        rdata1 = regs[raddr1];
        rdata2 = regs[raddr2];
    end
    always_ff @(posedge clk or negedge rst_n) begin
        if ((!rst_n)) begin
            regs[0] <= 1'd0;
            regs[1] <= 1'd0;
            regs[2] <= 1'd0;
            regs[3] <= 1'd0;
            regs[4] <= 1'd0;
            regs[5] <= 1'd0;
            regs[6] <= 1'd0;
            regs[7] <= 1'd0;
        end else if (we) begin
            regs[waddr] <= wdata;
        end
    end
endmodule