// Generated by PyHDL Transpiler
// Source: C:\Users\tkyke\OneDrive\Desktop\pyhdl\test_code\09_param_inst.phd

module TopInstantiation (
    input logic [7:0] in_8a,
    input logic [7:0] in_8b,
    input logic carry_in,
    input logic [15:0] in_16a,
    input logic [15:0] in_16b,
    output logic [8:0] sum_8,
    output logic [16:0] sum_16,
    output logic [15:0] prod_8,
    output logic [31:0] prod_16,
    output logic cmp_eq,
    output logic cmp_lt,
    output logic cmp_gt
);
    logic [8:0] u_add8_sum;
    logic [16:0] u_add16_sum;
    logic [15:0] u_mul8_product;
    logic [31:0] u_mul16_product;
    logic u_cmp_eq;
    logic u_cmp_lt;
    logic u_cmp_gt;
    ParamAdder_width8 u_add8 (.a(in_8a), .b(in_8b), .cin(carry_in), .sum(u_add8_sum));
    ParamAdder_width16 u_add16 (.a(in_16a), .b(in_16b), .cin(1'd0), .sum(u_add16_sum));
    ParamMultiplier_width8 u_mul8 (.a(in_8a), .b(in_8b), .product(u_mul8_product));
    ParamMultiplier_width16 u_mul16 (.a(in_16a), .b(in_16b), .product(u_mul16_product));
    ParamComparator_width8 u_cmp (.a(in_8a), .b(in_8b), .eq(u_cmp_eq), .lt(u_cmp_lt), .gt(u_cmp_gt));
    always_comb begin
        sum_8 = u_add8_sum;
        sum_16 = u_add16_sum;
        prod_8 = u_mul8_product;
        prod_16 = u_mul16_product;
        cmp_eq = u_cmp_eq;
        cmp_lt = u_cmp_lt;
        cmp_gt = u_cmp_gt;
    end
endmodule

module ParamAdder_width8 (
    input logic [7:0] a,
    input logic [7:0] b,
    input logic cin,
    output logic [8:0] sum
);
    always_comb begin
        sum = ((a + b) + cin);
    end
endmodule

module ParamAdder_width16 (
    input logic [15:0] a,
    input logic [15:0] b,
    input logic cin,
    output logic [16:0] sum
);
    always_comb begin
        sum = ((a + b) + cin);
    end
endmodule

module ParamMultiplier_width8 (
    input logic [7:0] a,
    input logic [7:0] b,
    output logic [15:0] product
);
    always_comb begin
        product = (a * b);
    end
endmodule

module ParamMultiplier_width16 (
    input logic [15:0] a,
    input logic [15:0] b,
    output logic [31:0] product
);
    always_comb begin
        product = (a * b);
    end
endmodule

module ParamComparator_width8 (
    input logic [7:0] a,
    input logic [7:0] b,
    output logic eq,
    output logic lt,
    output logic gt
);
    always_comb begin
        eq = (a == b);
        lt = (a < b);
        gt = (a > b);
    end
endmodule