// Generated by PyHDL Transpiler
// Source: C:\Users\tkyke\OneDrive\Desktop\pyhdl\test_code\demo_alu.phd

module SimpleALU (
    input logic [7:0] a,
    input logic [7:0] b,
    input logic [3:0] op,
    output logic [7:0] result,
    output logic zero,
    output logic carry,
    output logic overflow
);
    logic [8:0] temp;
    always_comb begin
        result = 8'd0;
        zero = 1'd0;
        carry = 1'd0;
        overflow = 1'd0;
        temp = 9'd0;
        unique case (op)
            0: begin
                temp = (a + b);
                result = temp[7:0];
                carry = temp[8];
                overflow = ((a[7] == b[7]) && (a[7] != result[7]));
            end
            1: begin
                temp = (a - b);
                result = temp[7:0];
                carry = temp[8];
                overflow = ((a[7] != b[7]) && (b[7] == result[7]));
            end
            2: begin
                result = (a & b);
            end
            3: begin
                result = (a | b);
            end
            4: begin
                result = (a ^ b);
            end
            5: begin
                result = (~(a | b));
            end
            6: begin
                if ((a < b)) begin
                    result = 8'd1;
                end else begin
                    result = 8'd0;
                end
            end
            7: begin
                result = (a << b[2:0]);
            end
        endcase
        if ((result == 0)) begin
            zero = 1'd1;
        end
    end
endmodule

module ALU_TestTop (
    input logic [7:0] sys_a,
    input logic [7:0] sys_b,
    input logic [3:0] sys_op,
    output logic [7:0] sys_result,
    output logic sys_zero,
    output logic sys_carry,
    output logic sys_overflow
);
    logic [7:0] u_alu_result;
    logic u_alu_zero;
    logic u_alu_carry;
    logic u_alu_overflow;
    SimpleALU u_alu (.a(sys_a), .b(sys_b), .op(sys_op), .result(u_alu_result), .zero(u_alu_zero), .carry(u_alu_carry), .overflow(u_alu_overflow));
    always_comb begin
        sys_result = u_alu_result;
        sys_zero = u_alu_zero;
        sys_carry = u_alu_carry;
        sys_overflow = u_alu_overflow;
    end
endmodule