// Generated by PyHDL Transpiler
// Source: C:\Users\tkyke\OneDrive\Desktop\pyhdl\test_code\demo_traffic_light.phd

module TrafficLight (
    input logic clk,
    input logic rst_n,
    input logic tick,
    input logic emergency,
    output logic main_red,
    output logic main_yellow,
    output logic main_green,
    output logic side_red,
    output logic side_yellow,
    output logic side_green
);
    typedef enum logic [2:0] {MAIN_GREEN=3'd0, MAIN_YELLOW=3'd1, SIDE_GREEN=3'd2, SIDE_YELLOW=3'd3, EMERGENCY=3'd4} State_t;
    State_t state;
    logic [3:0] counter;
    always_comb begin
        main_red = 1'd0;
        main_yellow = 1'd0;
        main_green = 1'd0;
        side_red = 1'd0;
        side_yellow = 1'd0;
        side_green = 1'd0;
        unique case (state)
            MAIN_GREEN: begin
                main_green = 1'd1;
                side_red = 1'd1;
            end
            MAIN_YELLOW: begin
                main_yellow = 1'd1;
                side_red = 1'd1;
            end
            SIDE_GREEN: begin
                main_red = 1'd1;
                side_green = 1'd1;
            end
            SIDE_YELLOW: begin
                main_red = 1'd1;
                side_yellow = 1'd1;
            end
            EMERGENCY: begin
                main_red = 1'd1;
                side_red = 1'd1;
            end
            default: begin
            end
        endcase
    end
    always_ff @(posedge clk or negedge rst_n) begin
        if ((!rst_n)) begin
            state <= MAIN_GREEN;
            counter <= 4'd0;
        end else if (emergency) begin
            state <= EMERGENCY;
            counter <= 4'd0;
        end else begin
            unique case (state)
                MAIN_GREEN: begin
                    if (tick) begin
                        if ((counter == (10 - 1))) begin
                            state <= MAIN_YELLOW;
                            counter <= 4'd0;
                        end else begin
                            counter <= (counter + 1);
                        end
                    end
                end
                MAIN_YELLOW: begin
                    if (tick) begin
                        if ((counter == (3 - 1))) begin
                            state <= SIDE_GREEN;
                            counter <= 4'd0;
                        end else begin
                            counter <= (counter + 1);
                        end
                    end
                end
                SIDE_GREEN: begin
                    if (tick) begin
                        if ((counter == (10 - 1))) begin
                            state <= SIDE_YELLOW;
                            counter <= 4'd0;
                        end else begin
                            counter <= (counter + 1);
                        end
                    end
                end
                SIDE_YELLOW: begin
                    if (tick) begin
                        if ((counter == (3 - 1))) begin
                            state <= MAIN_GREEN;
                            counter <= 4'd0;
                        end else begin
                            counter <= (counter + 1);
                        end
                    end
                end
                EMERGENCY: begin
                    state <= MAIN_GREEN;
                    counter <= 4'd0;
                end
                default: begin
                end
            endcase
        end
    end
endmodule

module SimpleTrafficLight (
    input logic clk,
    input logic rst_n,
    input logic tick,
    output logic red,
    output logic yellow,
    output logic green
);
    typedef enum logic [1:0] {RED=2'd0, GREEN=2'd1, YELLOW=2'd2} Light_t;
    Light_t state;
    logic [3:0] count;
    always_comb begin
        red = 1'd0;
        yellow = 1'd0;
        green = 1'd0;
        unique case (state)
            RED: begin
                red = 1'd1;
            end
            GREEN: begin
                green = 1'd1;
            end
            YELLOW: begin
                yellow = 1'd1;
            end
            default: begin
            end
        endcase
    end
    always_ff @(posedge clk or negedge rst_n) begin
        if ((!rst_n)) begin
            state <= RED;
            count <= 4'd0;
        end else if (tick) begin
            unique case (state)
                RED: begin
                    if ((count == 5)) begin
                        state <= GREEN;
                        count <= 4'd0;
                    end else begin
                        count <= (count + 1);
                    end
                end
                GREEN: begin
                    if ((count == 8)) begin
                        state <= YELLOW;
                        count <= 4'd0;
                    end else begin
                        count <= (count + 1);
                    end
                end
                YELLOW: begin
                    if ((count == 2)) begin
                        state <= RED;
                        count <= 4'd0;
                    end else begin
                        count <= (count + 1);
                    end
                end
                default: begin
                end
            endcase
        end
    end
endmodule